Bump min required KF5 version
Otherwise fails with:
  src/pimcommonautocorrection/autocorrection/widgets/autocorrectionwidget.cpp:654:44: error: no member named 'PrimaryAction' in 'KMessageBox::ButtonCode'