Fix build failing due to ambigous overload
Fixes the following:

/messagetextedit.cpp:183:46: error: use of overloaded operator '+' is ambiguous (with operand types 'QChar' and 'QChar')
        cursor.insertText(QString(formatChar + formatChar));
                                  ~~~~~~~~~~ ^ ~~~~~~~~~~
/usr/include/qt/QtCore/qstring.h:1532:22: note: candidate function
inline const QString operator+(const QString &s1, QChar s2)
                     ^
/usr/include/qt/QtCore/qstring.h:1534:22: note: candidate function
inline const QString operator+(QChar s1, const QString &s2)